SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE `vocabularies` (
  `id` int(11) NOT NULL,
  `german` varchar(75) NOT NULL,
  `infinitive` varchar(75) NOT NULL,
  `simple_past` varchar(75) NOT NULL,
  `past_participle` varchar(75) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

INSERT INTO `vocabularies` (`id`, `german`, `infinitive`, `simple_past`, `past_participle`) VALUES
(1, 'sein', 'be', 'was, were', 'been'),
(2, 'etwas tragen', 'bear', 'bore', 'borne'),
(3, 'schlagen', 'beat', 'beat', 'beaten'),
(4, 'werden', 'become', 'became', 'become'),
(5, 'beginnen, anfangen', 'begin', 'began', 'begun'),
(6, 'biegen', 'bend', 'bent', 'bent'),
(7, 'wetten', 'bet', 'bet', 'bet'),
(8, 'bieten', 'bid', 'bid, bade', 'bid, bidden'),
(9, 'binden', 'bind', 'bound', 'bound'),
(10, 'beißen, stechen', 'bite', 'bit', 'bitten'),
(11, 'bluten', 'bleed', 'bled', 'bled'),
(12, 'blasen', 'blow', 'blew', 'blown'),
(13, 'zerbrechen, brechen, kaputtgehen', 'break', 'broke', 'broken'),
(14, 'züchten', 'breed', 'bred', 'bred'),
(15, 'mitbringen, herbringen, bringen', 'bring', 'brought', 'brought'),
(16, 'senden, übertragen, ausstrahlen', 'broadcast', 'broadcast', 'broadcast'),
(17, 'bauen', 'build', 'built', 'built'),
(18, 'brennen, verbrennen', 'burn', 'burnt', 'burnt'),
(19, 'zerplatzen, platzen', 'burst', 'burst', 'burst'),
(20, 'kaputtgehen', 'bust', 'bust', 'bust'),
(21, 'kaufen', 'buy', 'bought', 'bought'),
(22, 'werfen', 'cast', 'cast', 'cast'),
(23, 'fangen', 'catch', 'caught', 'caught'),
(24, 'auswählen, wählen, aussuchen', 'choose', 'chose', 'chosen'),
(25, 'sich klammern, klammern, festhalten', 'cling', 'clung', 'clung'),
(26, 'kommen', 'come', 'came', 'come'),
(27, 'kosten', 'cost', 'cost', 'cost'),
(28, 'kriechen, schleichen', 'creep', 'crept', 'crept'),
(29, 'ausschneiden, schneiden', 'cut', 'cut', 'cut'),
(30, 'verhandeln, verteilen', 'deal', 'dealt', 'dealt'),
(31, 'graben', 'dig', 'dug', 'dug'),
(32, 'tauchen', 'dive', 'dived', 'dived'),
(33, 'tun, machen', 'do', 'did', 'done'),
(34, 'zeichnen', 'draw', 'drew', 'drawn'),
(35, 'träumen', 'dream', 'dreamt', 'dreamt'),
(36, 'trinken', 'drink', 'drank', 'drunk'),
(37, 'ein Fahrzeug führen', 'drive', 'drove', 'driven'),
(38, 'essen', 'eat', 'ate', 'eaten'),
(39, 'hinfallen, fallen', 'fall', 'fell', 'fallen'),
(40, 'füttern', 'feed', 'fed', 'fed'),
(41, 'fühlen, sich fühlen', 'feel', 'felt', 'felt'),
(42, 'kämpfen', 'fight', 'fought', 'fought'),
(43, 'finden', 'find', 'found', 'found'),
(44, 'fliehen, flüchtern', 'flee', 'fled', 'fled'),
(45, 'schleudern', 'fling', 'flung', 'flung'),
(46, 'fliegen', 'fly', 'flew', 'flown'),
(47, 'verbieten', 'forbid', 'forbade, forbad', 'forbidden'),
(48, 'vorhersagen, prognostizieren', 'forecast', 'forecast', 'forecast'),
(49, 'vergessen', 'forget', 'forgot', 'forgotten'),
(50, 'jemand verlassen, verlassen, etwas aufgeben, aufgeben', 'forsake', 'forsook', 'forsaken'),
(51, 'frieren', 'freeze', 'froze', 'frozen'),
(52, 'bekommen, kriegen, holen, besorgen', 'get', 'got', 'got'),
(53, 'geben', 'give', 'gave', 'given'),
(54, 'zerkleinern, mahlen', 'grind', 'ground', 'ground'),
(55, 'gehen', 'go', 'went', 'gone'),
(56, 'wachsen', 'grow', 'grew', 'grown'),
(57, 'hängen, aufhängen', 'hang', 'hung', 'hung'),
(58, 'haben', 'have', 'had', 'had'),
(59, 'hören', 'hear', 'heard', 'heard'),
(60, 'verstecken', 'hide', 'hid', 'hidden'),
(61, 'jemanden schlagen, etwas schlagen, treffen', 'hit', 'hit', 'hit'),
(62, 'halten', 'hold', 'held', 'held'),
(63, 'verletzen', 'hurt', 'hurt', 'hurt'),
(64, 'behalten, halten', 'keep', 'kept', 'kept'),
(65, 'wissen, kennen', 'know', 'knew', 'known'),
(66, 'legen', 'lay', 'laid', 'laid'),
(67, 'führen, leiten', 'lead', 'led', 'led'),
(68, 'lernen', 'learn', 'learnt', 'learnt'),
(69, 'verlassen, weggehen, abfahren', 'leave', 'left', 'left'),
(70, 'verleihen', 'lend', 'lent', 'lent'),
(71, 'lassen', 'let', 'let', 'let'),
(72, 'liegen', 'lie', 'lay', 'lain'),
(73, 'anzünden', 'light', 'lit', 'lit'),
(74, 'verlieren', 'lose', 'lost', 'lost'),
(75, 'machen, herstellen', 'make', 'made', 'made'),
(76, 'bedeuten', 'mean', 'meant', 'meant'),
(77, 'sich treffen, treffen', 'meet', 'met', 'met'),
(78, 'überholen', 'overtake', 'overtook', 'overtaken'),
(79, 'bezahlen', 'pay', 'paid', 'paid'),
(80, 'beweisen', 'prove', 'proved', 'proven'),
(81, 'legen, stellen, wohin tun, tun', 'put', 'put', 'put'),
(82, 'verlassen, aufhören', 'quit', 'quit', 'quit'),
(83, 'lesen', 'read', 'read', 'read'),
(84, 'jemand von etwas befreien, befreien', 'rid', 'rid', 'rid'),
(85, 'reiten, Rad fahren, fahren', 'ride', 'rode', 'ridden'),
(86, 'klingeln, läuten', 'ring', 'rang', 'rung'),
(87, 'aufgehen, ansteigen', 'rise', 'rose', 'risen'),
(88, 'rennen, laufen', 'run', 'ran', 'run'),
(89, 'sagen', 'say', 'said', 'said'),
(90, 'sehen, besuchen', 'see', 'saw', 'seen'),
(91, 'suchen', 'seek', 'sought', 'sought'),
(92, 'verkaufen', 'sell', 'sold', 'sold'),
(93, 'schicken, senden an', 'send', 'sent', 'sent'),
(94, 'setzen, stellen, legen', 'set', 'set', 'set'),
(95, 'nähen', 'sew', 'sewed', 'sewn'),
(96, 'schütteln, zittern', 'shake', 'shook', 'shaken'),
(97, 'Schafe scheren, scheren, abbrechen', 'shear', 'sheared', 'shorn'),
(98, 'abstoßen, ablegen', 'shed', 'shed', 'shed'),
(99, 'scheinen', 'shine', 'shone', 'shone'),
(100, 'schießen', 'shoot', 'shot', 'shot'),
(101, 'zeigen', 'show', 'showed', 'shown'),
(102, 'schließen', 'shut', 'shut', 'shut'),
(103, 'singen', 'sing', 'sang', 'sung'),
(104, 'sinken, untergehen', 'sink', 'sank', 'sunk'),
(105, 'sitzen, sich setzen', 'sit', 'sat', 'sat'),
(106, 'erlegen, bezwingen', 'slay', 'slew', 'slain'),
(107, 'schlafen', 'sleep', 'slept', 'slept'),
(108, 'gleiten, rutschen', 'slide', 'slid', 'slid'),
(109, 'werfen, schleudern', 'sling', 'slung', 'slung'),
(110, 'schleichen', 'slink', 'slunk', 'slunk'),
(111, 'aufschlitzen', 'slit', 'slit', 'slit'),
(112, 'säen', 'sow', 'sowed', 'sown'),
(113, 'sprechen', 'speak', 'spoke', 'spoken'),
(114, 'sausen, flitzen, rasen', 'speed', 'sped', 'sped'),
(115, 'Geld ausgeben, Zeit verbringen', 'spend', 'spent', 'spent'),
(116, 'drehen, rotieren', 'spin', 'spun', 'spun'),
(117, 'spucken', 'spit', 'spat, spit', 'spat, spit'),
(118, 'teilen', 'split', 'split', 'split'),
(119, 'sich ausbreiten, ausbreiten, verteilen', 'spread', 'spread', 'spread'),
(120, 'aufspringen', 'spring', 'sprang', 'sprung'),
(121, 'stehen, sich hinstellen', 'stand', 'stood', 'stood'),
(122, 'stehlen', 'steal', 'stole', 'stolen'),
(123, 'kleben, stecken bleiben', 'stick', 'stuck', 'stuck'),
(124, 'stechen', 'sting', 'stung', 'stung'),
(125, 'stinken', 'stink', 'stank, stunk', 'stunk'),
(126, 'auf etwas zugehen, zugehen', 'stride', 'strode', 'stridden'),
(127, 'schlagen, treffen', 'strike', 'struck', 'struck'),
(128, 'auffädeln, aufziehen', 'string', 'strung', 'strung'),
(129, 'sich bemühen, bemühen', 'strive', 'strove', 'striven'),
(130, 'schwören', 'swear', 'swore', 'sworn'),
(131, 'kehren', 'sweep', 'swept', 'swept'),
(132, 'anwachsen, anschwellen', 'swell', 'swelled', 'swollen'),
(133, 'schwimmen', 'swim', 'swam', 'swum'),
(134, 'schwingen', 'swing', 'swung', 'swung'),
(135, 'mitnehmen, nehmen, wegbringen, bringen, dauern', 'take', 'took', 'taken'),
(136, 'lehren, unterrichten', 'teach', 'taught', 'taught'),
(137, 'zerreißen', 'tear', 'tore', 'torn'),
(138, 'erzählen, berichten', 'tell', 'told', 'told'),
(139, 'nachdenken, denken, meinen, glauben', 'think', 'thought', 'thought'),
(140, 'gedeihen', 'thrive', 'throve', 'thrived'),
(141, 'werfen', 'throw', 'threw', 'thrown'),
(142, 'stoßen', 'thrust', 'thrust', 'thrust'),
(143, 'treten', 'thread', 'throd', 'throdden, throd'),
(144, 'verstehen', 'understand', 'understood', 'understood'),
(145, 'wecken', 'wake', 'woke', 'woken'),
(146, 'anhaben, Kleidung tragen', 'wear', 'wore', 'worn'),
(147, 'weben', 'weave', 'wove', 'woven'),
(148, 'weinen', 'weep', 'wept', 'wept'),
(149, 'befeuchten', 'wet', 'wet', 'wet'),
(150, 'gewinnen', 'win', 'won', 'won'),
(151, 'schlängeln, spulen', 'wind', 'wound', 'wound'),
(152, 'auswringen, wringen', 'wring', 'wrung', 'wrung'),
(153, 'schreiben', 'write', 'wrote', 'written');

ALTER TABLE `vocabularies`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `vocabularies`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=155;
COMMIT;
